/**
 * BackpackModal - Smart packing list modal
 *
 * Displays AI-generated packing recommendations with:
 * - Water requirement summary
 * - Categorized items (Essentials, Clothing, Gear)
 * - Checkboxes for tracking packed items
 * - Rationale chips for weather-dependent items
 *
 * NO FAKE DATA - all items generated by PackingManager
 */

import React, { useState, useMemo, useRef, useEffect } from 'react';
import {
  View,
  Text,
  TouchableOpacity,
  StyleSheet,
  Modal,
  SectionList,
  SectionListRenderItemInfo,
  Animated,
} from 'react-native';
import { haptics } from '../../utils/haptics';
import { Ionicons } from '@expo/vector-icons';
import { colors, spacing, typography, borderRadius, shadows } from '../../theme/tokens';
import { PackingList, PackingItem, PackingCategory, PackingSection } from '../../features/packing/types';

interface BackpackModalProps {
  visible: boolean;
  packingList: PackingList;
  onClose: () => void;
}

/**
 * Category display configuration
 */
const CATEGORY_CONFIG: Record<PackingCategory, { title: string; icon: keyof typeof Ionicons.glyphMap }> = {
  essentials: { title: 'ESSENTIALS', icon: 'shield-checkmark' },
  clothing: { title: 'CLOTHING', icon: 'shirt' },
  gear: { title: 'GEAR', icon: 'construct' },
};

/**
 * Checkbox component
 */
function Checkbox({ checked, onToggle }: { checked: boolean; onToggle: () => void }) {
  return (
    <TouchableOpacity style={styles.checkboxContainer} onPress={onToggle}>
      <View style={[styles.checkbox, checked && styles.checkboxChecked]}>
        {checked && <Ionicons name="checkmark" size={16} color="#FFFFFF" />}
      </View>
    </TouchableOpacity>
  );
}

/**
 * Individual packing item row
 */
function PackingItemRow({
  item,
  checked,
  onToggle,
}: {
  item: PackingItem;
  checked: boolean;
  onToggle: () => void;
}) {
  // Format display name with quantity if present
  const displayName = item.quantity
    ? `${item.name} (${item.quantity}${item.unit || ''})`
    : item.name;

  return (
    <TouchableOpacity style={styles.itemRow} onPress={onToggle} activeOpacity={0.7}>
      <Checkbox checked={checked} onToggle={onToggle} />
      <View style={styles.itemIcon}>
        <Ionicons
          name={item.icon as keyof typeof Ionicons.glyphMap}
          size={20}
          color={checked ? colors.textTertiary : colors.primary}
        />
      </View>
      <Text style={[styles.itemName, checked && styles.itemNameChecked]}>
        {displayName}
      </Text>
      {item.rationale && (
        <View style={styles.rationaleChip}>
          <Text style={styles.rationaleText}>{item.rationale}</Text>
        </View>
      )}
    </TouchableOpacity>
  );
}

/**
 * Section header component
 */
function SectionHeader({ section }: { section: PackingSection }) {
  const config = CATEGORY_CONFIG[section.category];
  return (
    <View style={styles.sectionHeader}>
      <Ionicons name={config.icon} size={16} color={colors.textSecondary} />
      <Text style={styles.sectionTitle}>{config.title}</Text>
    </View>
  );
}

/**
 * Water summary chip
 */
function WaterSummary({ liters }: { liters: number }) {
  return (
    <View style={styles.waterSummary}>
      <Ionicons name="water" size={20} color={colors.info} />
      <Text style={styles.waterText}>
        {liters}L Water Required
      </Text>
      {liters >= 3 && (
        <View style={styles.warningChip}>
          <Text style={styles.warningText}>Heavy Load</Text>
        </View>
      )}
    </View>
  );
}

/**
 * BackpackModal Component
 */
export function BackpackModal({ visible, packingList, onClose }: BackpackModalProps) {
  // Track checked state for each item
  const [checkedItems, setCheckedItems] = useState<Set<string>>(new Set());

  // Group items into sections for SectionList
  const sections: PackingSection[] = useMemo(() => {
    const grouped: Record<PackingCategory, PackingItem[]> = {
      essentials: [],
      clothing: [],
      gear: [],
    };

    packingList.items.forEach((item) => {
      grouped[item.category].push(item);
    });

    return (['essentials', 'clothing', 'gear'] as PackingCategory[])
      .filter((category) => grouped[category].length > 0)
      .map((category) => ({
        title: CATEGORY_CONFIG[category].title,
        category,
        data: grouped[category],
      }));
  }, [packingList]);

  // Toggle item checked state with haptic feedback
  const toggleItem = (itemId: string) => {
    haptics.impact('light');
    setCheckedItems((prev) => {
      const next = new Set(prev);
      if (next.has(itemId)) {
        next.delete(itemId);
      } else {
        next.add(itemId);
      }
      return next;
    });
  };

  // Calculate progress
  const totalItems = packingList.items.length;
  const packedItems = checkedItems.size;
  const progressPercent = totalItems > 0 ? (packedItems / totalItems) * 100 : 0;

  // Animated progress bar
  const progressAnim = useRef(new Animated.Value(0)).current;

  useEffect(() => {
    Animated.timing(progressAnim, {
      toValue: progressPercent,
      duration: 300,
      useNativeDriver: false,
    }).start();
  }, [progressPercent, progressAnim]);

  // Render item
  const renderItem = ({ item }: SectionListRenderItemInfo<PackingItem, PackingSection>) => (
    <PackingItemRow
      item={item}
      checked={checkedItems.has(item.id)}
      onToggle={() => toggleItem(item.id)}
    />
  );

  // Render section header
  const renderSectionHeader = ({ section }: { section: PackingSection }) => (
    <SectionHeader section={section} />
  );

  return (
    <Modal
      visible={visible}
      transparent
      animationType="slide"
      statusBarTranslucent
      onRequestClose={onClose}
    >
      <View style={styles.overlay}>
        <View style={styles.container}>
          {/* Header */}
          <View style={styles.header}>
            <Text style={styles.headerIcon}>🎒</Text>
            <Text style={styles.headerTitle}>Your Smart Pack</Text>
            <TouchableOpacity style={styles.closeButton} onPress={onClose}>
              <Ionicons name="close" size={24} color={colors.textSecondary} />
            </TouchableOpacity>
          </View>

          {/* Water Summary */}
          <WaterSummary liters={packingList.waterLiters} />

          {/* Progress Bar */}
          <View style={styles.progressContainer}>
            <View style={styles.progressBar}>
              <Animated.View
                style={[
                  styles.progressFill,
                  {
                    width: progressAnim.interpolate({
                      inputRange: [0, 100],
                      outputRange: ['0%', '100%'],
                    }),
                  },
                ]}
              />
            </View>
            <Text style={styles.progressText}>
              {packedItems}/{totalItems} items packed
            </Text>
          </View>

          {/* Items List */}
          <SectionList
            sections={sections}
            renderItem={renderItem}
            renderSectionHeader={renderSectionHeader}
            keyExtractor={(item) => item.id}
            style={styles.list}
            contentContainerStyle={styles.listContent}
            stickySectionHeadersEnabled={false}
            showsVerticalScrollIndicator={false}
          />

          {/* Weather Factors */}
          {packingList.weatherFactors.length > 0 && (
            <View style={styles.factorsContainer}>
              <Text style={styles.factorsLabel}>Based on:</Text>
              <View style={styles.factorChips}>
                {packingList.weatherFactors.map((factor, index) => (
                  <View key={index} style={styles.factorChip}>
                    <Text style={styles.factorText}>{factor}</Text>
                  </View>
                ))}
              </View>
            </View>
          )}

          {/* I'm Ready Button */}
          <TouchableOpacity
            style={[
              styles.readyButton,
              progressPercent === 100 && styles.readyButtonComplete,
            ]}
            onPress={onClose}
          >
            <Ionicons
              name={progressPercent === 100 ? 'checkmark-circle' : 'bag-check'}
              size={24}
              color="#FFFFFF"
            />
            <Text style={styles.readyButtonText}>
              {progressPercent === 100 ? "All Packed!" : "I'm Ready!"}
            </Text>
          </TouchableOpacity>
        </View>
      </View>
    </Modal>
  );
}

const styles = StyleSheet.create({
  overlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.6)',
    justifyContent: 'flex-end',
  },
  container: {
    backgroundColor: colors.surface,
    borderTopLeftRadius: borderRadius.xl,
    borderTopRightRadius: borderRadius.xl,
    maxHeight: '85%',
    paddingBottom: spacing.xl,
  },

  // Header
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: spacing.lg,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: colors.borderLight,
  },
  headerIcon: {
    fontSize: 28,
    marginRight: spacing.sm,
  },
  headerTitle: {
    ...typography.title2,
    color: colors.text,
    flex: 1,
  },
  closeButton: {
    padding: spacing.xs,
  },

  // Water Summary
  waterSummary: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: `${colors.info}15`,
    marginHorizontal: spacing.lg,
    marginTop: spacing.md,
    padding: spacing.md,
    borderRadius: borderRadius.lg,
    gap: spacing.sm,
  },
  waterText: {
    ...typography.headline,
    color: colors.info,
    flex: 1,
  },
  warningChip: {
    backgroundColor: colors.warning,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
    borderRadius: borderRadius.sm,
  },
  warningText: {
    ...typography.caption2,
    color: '#FFFFFF',
    fontWeight: '600',
  },

  // Progress
  progressContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: spacing.lg,
    marginTop: spacing.md,
    gap: spacing.sm,
  },
  progressBar: {
    flex: 1,
    height: 6,
    backgroundColor: colors.borderLight,
    borderRadius: 3,
    overflow: 'hidden',
  },
  progressFill: {
    height: '100%',
    backgroundColor: colors.success,
    borderRadius: 3,
  },
  progressText: {
    ...typography.caption1,
    color: colors.textSecondary,
    minWidth: 80,
    textAlign: 'right',
  },

  // List
  list: {
    flex: 1,
    marginTop: spacing.sm,
  },
  listContent: {
    paddingHorizontal: spacing.lg,
    paddingBottom: spacing.md,
  },

  // Section Header
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingTop: spacing.lg,
    paddingBottom: spacing.sm,
    gap: spacing.xs,
  },
  sectionTitle: {
    ...typography.caption1,
    color: colors.textSecondary,
    fontWeight: '600',
    letterSpacing: 1,
  },

  // Item Row
  itemRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: spacing.sm,
    gap: spacing.sm,
  },
  checkboxContainer: {
    padding: spacing.xs,
  },
  checkbox: {
    width: 24,
    height: 24,
    borderRadius: borderRadius.sm,
    borderWidth: 2,
    borderColor: colors.primary,
    justifyContent: 'center',
    alignItems: 'center',
  },
  checkboxChecked: {
    backgroundColor: colors.primary,
    borderColor: colors.primary,
  },
  itemIcon: {
    width: 32,
    alignItems: 'center',
  },
  itemName: {
    ...typography.body,
    color: colors.text,
    flex: 1,
  },
  itemNameChecked: {
    color: colors.textTertiary,
    textDecorationLine: 'line-through',
  },
  rationaleChip: {
    backgroundColor: `${colors.primary}15`,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
    borderRadius: borderRadius.sm,
  },
  rationaleText: {
    ...typography.caption2,
    color: colors.primary,
  },

  // Weather Factors
  factorsContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: spacing.lg,
    marginTop: spacing.sm,
    gap: spacing.sm,
  },
  factorsLabel: {
    ...typography.caption1,
    color: colors.textSecondary,
  },
  factorChips: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.xs,
    flex: 1,
  },
  factorChip: {
    backgroundColor: colors.background,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
    borderRadius: borderRadius.sm,
  },
  factorText: {
    ...typography.caption2,
    color: colors.textSecondary,
  },

  // Ready Button
  readyButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.primary,
    marginHorizontal: spacing.lg,
    marginTop: spacing.lg,
    padding: spacing.md,
    borderRadius: borderRadius.lg,
    gap: spacing.sm,
    ...shadows.small,
  },
  readyButtonComplete: {
    backgroundColor: colors.success,
  },
  readyButtonText: {
    ...typography.headline,
    color: '#FFFFFF',
  },
});

export default BackpackModal;
